package com.yourname.spotifytodeezer.controller;

import com.yourname.spotifytodeezer.model.Track;
import com.yourname.spotifytodeezer.model.TransferRequest;
import com.yourname.spotifytodeezer.model.TransferResponse;
import com.yourname.spotifytodeezer.service.SpotifyService;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * REST Controller for Spotify-related endpoints
 *
 * @RestController - Combines @Controller and @ResponseBody
 * This means all methods return JSON data (not HTML views)
 *
 * @RequestMapping - All endpoints in this controller start with /api/spotify
 */
@RestController
@RequestMapping("/api/spotify")
public class SpotifyController {

    /**
     * Dependency Injection - Spring automatically injects SpotifyService
     *
     * @Autowired tells Spring: "Find a SpotifyService bean and inject it here"
     * This is one of Spring's core features - you don't need to create objects yourself
     */
    @Autowired
    private SpotifyService spotifyService;

    // Store tracks in memory for this demo (in Phase 2, we might use sessions)
    private List<Track> cachedTracks;

    /**
     * Endpoint to fetch playlist tracks
     *
     * POST /api/spotify/playlist
     * Request body: { "playlistUrl": "...", "clientId": "...", "clientSecret": "..." }
     * Response: { "tracks": [...] }
     *
     * @PostMapping - This method handles HTTP POST requests
     * @RequestBody - Automatically converts JSON to Java object
     */
    @PostMapping("/playlist")
    public ResponseEntity<?> getPlaylist(@RequestBody Map<String, String> request) {
        try {
            String playlistUrl = request.get("playlistUrl");
            String clientId = request.get("clientId");
            String clientSecret = request.get("clientSecret");

            // Validate input
            if (playlistUrl == null || clientId == null || clientSecret == null) {
                return ResponseEntity.badRequest()
                        .body(Map.of("error", "Missing required fields"));
            }

            // Call service to fetch tracks
            List<Track> tracks = spotifyService.getPlaylistTracks(
                    playlistUrl,
                    clientId,
                    clientSecret
            );

            // Cache tracks for later use
            this.cachedTracks = tracks;

            // Return success response with tracks
            return ResponseEntity.ok(Map.of("tracks", tracks));

        } catch (Exception e) {
            // Handle errors and return error response
            e.printStackTrace();
            return ResponseEntity.status(500)
                    .body(Map.of(
                            "error", "Failed to fetch playlist",
                            "details", e.getMessage()
                    ));
        }
    }

    /**
     * Endpoint for transfer/submit action
     *
     * POST /api/spotify/transfer
     * Request body: { "playlistName": "...", "selectedTrackIds": ["id1", "id2", ...] }
     * Response: [{ "isrc": "...", "title": "...", "artist": "..." }, ...]
     *
     * For Phase 1: Just returns JSON with ISRC, title, artist
     * For Phase 2: Will actually call Deezer API to create playlist
     */
    @PostMapping("/transfer")
    public ResponseEntity<?> transfer(@RequestBody TransferRequest request) { //requetbody = json to obj
        //since it's a trasnferRequest obj it can use getter generated by spring
        try {
            // Get selected track IDs from request
            List<String> selectedIds = request.getSelectedTrackIds();

            if (selectedIds == null || selectedIds.isEmpty()) {
                return ResponseEntity.badRequest()
                        .body(Map.of("error", "No tracks selected"));
            }

            // Filter cached tracks to only selected ones
            List<Track> selectedTracks = cachedTracks.stream()
                    .filter(track -> selectedIds.contains(track.getId()))
                    .collect(Collectors.toList());

            // Build response with ISRC, title, and artist for each selected track
            List<TransferResponse> response = selectedTracks.stream()
                    .map(track -> new TransferResponse(
                            track.getIsrc() != null ? track.getIsrc() : "NO_ISRC",
                            track.getName(),
                            String.join(", ", track.getArtists()) // Combine multiple artists
                    ))
                    .collect(Collectors.toList());

            // For Phase 1: Just return the JSON
            // In Phase 2, we'll add Deezer API call here
            return ResponseEntity.ok(response);

        } catch (Exception e) {
            e.printStackTrace();
            return ResponseEntity.status(500)
                    .body(Map.of(
                            "error", "Transfer failed",
                            "details", e.getMessage()
                    ));
        }
    }
}